server:
  port: 8094
spring:
  application:
    name: graphql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    mongodb:
      authentication-database: admin
      host: 192.168.2.196
      port: 27017
      database: jumper
      username: test
      password: 123456
  redis:
    host: 192.168.0.2
    port: 6379
    password: Redis@2016

  boot:
    admin:
      client:
        url: 127.0.0.1:8060
        username: "admin"
        password: "admin"
        instance:
          prefer-ip: true

#### 暴露端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS

logging:
  config: classpath:logging-config.xml
  level:
    org:
      springframework:
        web: info
  pattern:
    #     日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'