#server:
#  port: 10001
#spring:
#  application:
#    name: lonjoy-external-open-provider
#  cloud:
#    nacos:
#      discovery:
#        namespace: 1d607e88-f7ec-43b7-a18c-f669d415d488
#        server-addr: http://175.178.86.252:8848
#        metadata:
#          user.name: "admin"
#          user.password: "admin"
#  datasource:
#    # jdbc 连接基础配置
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/lonjoy_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #hikari数据源特性配置
#    hikari:
#      maximum-pool-size: 100 #最大连接数,默认值10.
#      minimum-idle: 20 #最小空闲连接，默认值10.
#      connection-timeout: 60000 #连接超时时间(毫秒),默认值30秒.
#      #空闲连接超时时间，默认值600000(10分钟),只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
#      #如果大于等于 max-lifetime 且 max-lifetime>0,则会被重置为0.
#      idle-timeout: 600000
#      max-lifetime: 3000000 #连接最大存活时间,默认值30分钟.设置应该比mysql设置的超时时间短
#      connection-test-query: select 1 #连接测试查询
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 1
#    # Redis服务器地址
#    host: 175.178.86.252
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: 123456@
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 10000ms
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0
#      # 连接超时时间（毫秒）
#      shutdown-timeout: 0
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false # 自动驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**.xml
#  type-aliases-package: com.lonjoy.auth.provider.model
#
#  boot:
#    admin:
#      client:
#        url: 127.0.0.1:8060
#        username: "admin"
#        password: "admin"
#        instance:
#          prefer-ip: true
## fegin配置
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000
#        exception:
#          timeout:
#            enable: false
##### 暴露端点
#management:
#  endpoints:
#    enabled-by-default: true
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#      show-details: ALWAYS
#
#logging:
#  config: classpath:logging-config.xml
#  level:
#    org:
#      springframework:
#        web: info
#  pattern:
#    #     日志高亮
#    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
