server:
  port: 8005
spring:
  application:
    name: oauth-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.20:8848
  boot:
    admin:
      client:
        url: 192.168.1.20:8060
        username: "admin"
        password: "admin"
        instance:
          prefer-ip: true
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.20:3306/sc_auth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  security:
    oauth2:
      jwt:
        signingKey: 123456
dubbo:
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: spring-cloud://localhost
#### 暴露端点
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
logging:
  config: classpath:logging-config.xml
  level:
    org:
      springframework:
        web: info
  pattern:
    #     日志高亮
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
