server:
  port: 9999
spring:
  application:
    name: gateway-dynamic-route
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.1.20:9999
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.20:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
      filter:
        enable: true
    nacos:
      discovery:
        server-addr: 192.168.1.20:8848
  boot:
    admin:
      client:
        url: 192.168.1.20:8060
        username: "admin"
        password: "admin"
        instance:
          prefer-ip: true

