
server:
  port: 2005
# 处理jvm信息
management:
  endpoints:
    web:
      exposure:
        include:  bus-refresh
  endpoint:
    bus-refresh:
      enabled: true
spring:
  application:
    name: client
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: wl_vhosts


