server:
  port: 9998
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  redis:
    host: 192.168.0.2
    port: 6379
    password: Redis@2016
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.20:8848

## hystrix 信号量隔离，3秒后自动超时
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
#  shareSecurityContext: true
#
#
## 注册中心
#eureka:
#  instance:
#    #prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8700/eureka/

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: debug



